In [2]:
import pandas as pd

In [20]:
data = pd.read_excel('data/sample_data.xlsx', sheet_name = 'anual').T
data.columns = data.loc['Indicador'].values
data.drop('Indicador', inplace = True)
#data = data.reset_index()

In [23]:
data

,Inflación (Variación punta a punta),Inflación (Promedio anual),Salarios (Var punta a punta),PBI (% vs PY),Consumo Privado (% vs PY),Inversión (% vs PY),Desempleo,TC Promedio Anual,TC Fin de Periodo
2012,0.0454011,0.0451734,0.073001,0.051,0.046,0.025,0.032,6.96,6.96
2013,0.0647968,0.057367,0.0736765,0.068,0.059,0.117,0.04,6.96,6.96
2014,0.0519425,0.057646,0.0771173,0.055,0.054,0.099,0.035,6.96,6.96
2015,0.0295315,0.0406108,0.0678895,0.049,0.052,0.05,0.046,6.96,6.96
2016,0.0400294,0.0362451,0.0258981,0.043,0.034,0.034,0.044,6.96,6.96
2017,0.0271467,0.0282245,0.0294373,0.042,0.0473078,0.118,0.045,6.96,6.96
2018,0.015068,0.0227163,0.0457303,0.042,0.0430131,0.032,0.0427,6.96,6.96
2019,0.0146904,0.0183928,-0.0178475,0.022167,0.0367588,-0.0346151,0.0483,6.96,6.96
2020,0.00670472,0.00941894,0.01076,-0.0879878,-0.083955,-0.171167,0.085,6.96,6.96
2021,0.0217258,0.0098113,0.0146928,0.0663835,0.0773791,0.0547135,0.063,6.96,6.96
2022,0.05,0.055,0.05,0.034,0.027,0.015,0.05,7.18,7.36
2023,0.05,0.05,0.06,0.03,0.03,0.05,0.04,7.62,7.84

In [17]:
def fix_anual_dates(date):
    return str(date) + '-01-01'

In [22]:
pd.to_datetime(data.index.apply(fix_anual_dates))

AttributeError: 'Index' object has no attribute 'apply'

In [ ]:
decomposed = sm.tsa.seasonal_decompose(data[variable].astype('float32'))